osx_image: xcode7.3
language: objective-c
xcode_sdk: iphonesimulator9.3

before_install:
- brew update
- if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
- if brew outdated | grep -qx carthage; then brew upgrade carthage; fi
- travis_wait 35 carthage bootstrap --platform iOS

script:
- xcodebuild clean build -project Spots.xcodeproj -scheme "Spots-iOS" -sdk iphonesimulator
- xcodebuild test -project Spots.xcodeproj -scheme "Spots-iOS" -sdk iphonesimulator
- xcodebuild clean build -project Spots.xcodeproj -scheme "Spots-Mac" -sdk iphonesimulator
- xcodebuild test -project Spots.xcodeproj -scheme "Spots-Mac" -sdk iphonesimulator
