version: 2
jobs:
  carthage:
    macos:
      xcode: "9.3.0"
    working_directory: /Users/distiller/project
    shell: /bin/bash --login -o pipefail
    steps:
      - run: brew upgrade Carthage
      - run: carthage bootstrap
      - run: brew install swiftlint
  build-and-test:
    macos:
      xcode: "9.3.0"
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run: xcodebuild -project Spots.xcodeproj -scheme "Spots-macOS" -sdk macosx clean
      - run: xcodebuild -project Spots.xcodeproj -scheme "Spots-macOS" -sdk macosx -enableCodeCoverage YES test
      - run: bash <(curl -s https://codecov.io/bash) -cF osx -J 'Spots'
      - run: xcodebuild -project Spots.xcodeproj -scheme "Spots-iOS" -sdk iphonesimulator clean
      - run: xcodebuild -project Spots.xcodeproj -scheme "Spots-iOS" -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=11.3,name=iPhone X' -enableCodeCoverage YES test
      - run: bash <(curl -s https://codecov.io/bash) -cF ios -J 'Spots'
      - run: xcodebuild -project Spots.xcodeproj -scheme "Spots-tvOS" -destination 'platform=tvOS Simulator,name=Apple TV,OS=11.3' clean
      - run: xcodebuild -project Spots.xcodeproj -scheme "Spots-tvOS" -destination 'platform=tvOS Simulator,name=Apple TV,OS=11.3' -enableCodeCoverage YES test
      - run: bash <(curl -s https://codecov.io/bash) -cF tvos -J 'Spots'

workflows:
  version: 2
  build-and-test:
    jobs:
      - carthage
      - build-and-test      